# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Research Project EUFoot
shorttitle: Home # Text for Link to home on all pages
email: 
description: >- # this means to ignore newlines until "baseurl:"
  The identity effect of Europeanised lifeworlds: Becoming European through football? (EUFoot) is a three year research project (2018-2021), conducted at the University of Mainz and
  Rhine-Waal University, Kleve, Germany. It is fully sponsored by the German Research Fund (DFG). 
baseurl: "" # the subpath of your site, e.g. /blog
url: "eufoot.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: eu_foot
github_username:  eufoot
researchgate: "https://www.researchgate.net/project/The-identity-effect-of-Europeanised-lifeworlds-Becoming-European-through-football" 

show_excerpts: true

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
